### ISSUE TITLE
Duplicate search results appearing

### ISSUE THREAD

**Issue by maya** [18F/jekyll_pages_api_search#34]
I'm getting the same set of results twice in my search results. I noticed this bc I saw it focusing on what I thought was a random result, but was actually the first result of the second duplication of results.

This is what it looks like:

<img width="512" alt="screen_shot_2016-07-13_at_8 09 55_am_1024" src="https://cloud.githubusercontent.com/assets/5249443/16808967/6d18dadc-48d3-11e6-8ea1-ac7439e5a38c.png">

This is my template code:

```

---
layout: default
header_border: true

---

<div class="usa-grid">
  {% jekyll_pages_api_search_interface %}
  {% jekyll_pages_api_search_results %}
</div>

{% jekyll_pages_api_search_load %}
```

**Comment by maya** [comment]
When I do not use the template above, and use what's default, I do not get duplicate results.

**Comment by afeld** [comment]
Turns out the search JS was being loaded twice on the site. Fixed in https://github.com/18F/beta.18f.gov/commit/e1d05b61c26d72953c62cbd346beedec5ab3f6e9.
