### ISSUE TITLE
Check for title in front matter

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/jekyll_pages_api_search#48]
I've noticed an issue where search result output page titles missing (see below). 

This appears to be due to a lack of front matter (README file) or lack of `title` in the front matter.

Consider adding check for the presence of front matter and/or `title` key or some other solution.

![Search results with missing title for second item](https://user-images.githubusercontent.com/32855580/74888689-8ea77c80-5333-11ea-843c-858840202589.png)

![Search results with missing title for second item](https://user-images.githubusercontent.com/32855580/74888688-8e0ee600-5333-11ea-8809-a2a5427bb72e.png)

**Comment by eddietejeda** [comment]
Good suggestion, but this repo is not active. Sites that want to use search should use search.gov. 

The new default Federalist theme now supports both inline search results (using JS) and rendered in search.gov domain.	

https://github.com/18F/federalist-uswds-jekyll

**Comment by brentryanjohnson** [comment]
Thanks @eddietejeda. Closing.
